#!/usr/bin/env bash

if [ "$1" == "clean" ]; then
        rm -rf Packages .build
	exit
fi

SB=`which swift-build`
ST="swift test"
$SB --fetch
rm -rf ./Packages/*/Tests
$SB

if [ "$1" == "test" ]; then
	$ST
fi
